### ISSUE TITLE
Resources Management

### ISSUE THREAD

**Issue by joelthe1** [BiblioNexus-Foundation/scribe-extensions#2]
- [x] Resource manager for supporting all modalities of resources in Codex and Scribe.
- [x] Decide on internals (should support local files)
- [ ] Integrate into Scribe

**Comment by brianineza01** [comment]
Currently fixing bugs for the resource manager, Once version 1 is released, the issue will be closed.

**Comment by joelthe1** [comment]
Closing this in favor of #14
